(()=>{
 const cfg=window.FM_FANTASY_CONFIG||{};if(!window.supabase||!cfg.supabaseUrl||!cfg.supabaseAnonKey)return;
 const client=supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),sleep=ms=>new Promise(r=>setTimeout(r,ms));let lastLeagueSig='';
 const rawHist=s=>Array.isArray(s?.pointsHistory)?s.pointsHistory:Array.isArray(s?.history)?s.history:null;
 const hist=s=>{const h=rawHist(s)||[],entry=Number(s?.entryGameweek||1)||1;return h.filter(x=>(Number(x?.gw)||0)>=entry)};
 const pts=s=>{const raw=rawHist(s);if(raw)return hist(s).reduce((n,x)=>n+Number(x?.net??x?.gross??0),0);return Number(s?.totalPoints||0)};
 const gwPts=(s,gw)=>{const r=hist(s).find(x=>Number(x?.gw)===Number(gw));return r?Number(r?.net??r?.gross??0):0};
 const memberFrom=(uid,s,p,selfUid)=>({own:uid===selfUid,name:p?.username||'Manager',team:s?.teamName||'My Team',points:pts(s),squad:[...(s?.squad||[])],starters:[...(s?.starters||[])],bench:[...(s?.bench||[])],captain:s?.captain||null,vice:s?.vice||null,entryGameweek:s?.entryGameweek||null,currentGameweek:s?.currentGameweek||null,teamConfirmed:!!s?.teamConfirmed,pointsHistory:[...hist(s)]});
 async function session(){return (await client.auth.getSession()).data.session}
 async function peerData(){const s=await session();if(!s||!window.FMCloud?.ready?.())return null;const world=window.FMCloud.getWorld?.();if(!world?.id)return null;const[{data:states,error:se},{data:profiles,error:pe}]=await Promise.all([client.from('manager_states').select('user_id,state').eq('world_id',world.id),client.from('profiles').select('user_id,username,role,created_at')]);if(se||pe)return null;return{s,world,states:states||[],profiles:new Map((profiles||[]).map(x=>[x.user_id,x]))}}
 async function syncNews(){try{const d=await peerData();if(!d||typeof state==='undefined')return;const cs=d.states.find(x=>x.user_id===d.world.creator_id)?.state||{};let news=cs.news||null,active=cs.activeStatuses||null,payload=await window.FMCloud.loadWorld?.();if(!news&&payload&&typeof fmBuildInitialNews==='function')news=fmBuildInitialNews(payload);if(!active&&news)active={injuries:news.injuries||[],suspensions:news.suspensions||[]};let c=false;if(news&&JSON.stringify(state.news)!==JSON.stringify(news)){state.news=news;c=true}if(active&&JSON.stringify(state.activeStatuses)!==JSON.stringify(active)){state.activeStatuses=active;c=true}if(c){if(typeof save==='function')save();if(typeof renderNews==='function')renderNews()}}catch(e){console.warn('Shared news sync failed',e)}}
 async function syncLeagues(){try{const d=await peerData();if(!d||typeof state==='undefined'||!Array.isArray(state.leagues))return;const all=[];for(const row of d.states){const st=row.state||{};for(const l of(st.leagues||[]))if(l?.code)all.push({uid:row.user_id,state:st,league:l,profile:d.profiles.get(row.user_id)})}let changed=false;for(const l of state.leagues){if(!l?.code)continue;const code=String(l.code).toUpperCase(),matches=all.filter(x=>String(x.league.code).toUpperCase()===code);if(!matches.length)continue;const canonical=matches.map(x=>x.league?.name).find(Boolean);if(canonical&&l.name!==canonical){l.name=canonical;changed=true}const seen=new Set(),members=[];for(const x of matches){if(seen.has(x.uid))continue;seen.add(x.uid);members.push(memberFrom(x.uid,x.state,x.profile,d.s.user.id))}members.sort((a,b)=>b.points-a.points||a.name.localeCompare(b.name));if(JSON.stringify(l.members||[])!==JSON.stringify(members)){l.members=members;changed=true}}const sig=JSON.stringify(state.leagues.map(l=>[l.code,(l.members||[]).map(m=>[m.name,m.points,m.own,m.entryGameweek])]));if(sig!==lastLeagueSig||changed){lastLeagueSig=sig;if(typeof renderLeagues==='function')renderLeagues();if(changed&&typeof save==='function')save()}setTimeout(()=>{beautifyFeaturedLeague();renderManagerSummary()},50)}catch(e){console.warn('Shared league sync failed',e)}}
 function viewingMember(){const banner=document.getElementById('viewBanner');if(!banner?.classList.contains('show')||typeof state==='undefined')return null;const txt=(banner.textContent||'').toLowerCase();const members=[];for(const l of(state.leagues||[]))for(const m of(l.members||[]))if(!m.own)members.push(m);members.sort((a,b)=>String(b.team||'').length-String(a.team||'').length);return members.find(m=>m.team&&txt.includes(String(m.team).toLowerCase()))||null}
 function selectedGw(member){const page=document.getElementById('teamPage');if(page){for(const el of page.querySelectorAll('*')){if(el.children.length)continue;const t=(el.textContent||'').trim(),m=t.match(/^Gameweek\s*(\d+)$/i)||t.match(/^GW\s*(\d+)$/i);if(m&&el.offsetParent!==null)return Number(m[1])}}return Number(member?.currentGameweek||state?.currentGameweek||1)}
 function renderManagerSummary(){const page=document.getElementById('teamPage'),banner=document.getElementById('viewBanner');if(!page||!banner)return;const active=banner.classList.contains('show'),member=active?viewingMember():null;page.classList.toggle('leagueReadOnly',!!member);let bar=document.getElementById('fmLeagueManagerSummary');if(!member){bar?.remove();return}const gw=selectedGw(member),gp=gwPts(member,gw),total=Number(member.points||0);if(!bar){bar=document.createElement('div');bar.id='fmLeagueManagerSummary';banner.insertAdjacentElement('afterend',bar)}bar.innerHTML=`<div class="fmMgrCell"><span>Team Name</span><b>${esc(member.team||'My Team')}</b></div><div class="fmMgrCell"><span>Manager</span><b>${esc(member.name||'Manager')}</b></div><div class="fmMgrCell"><span>Gameweek</span><b>GW ${gw} <em>${gp} pts</em></b></div><div class="fmMgrCell"><span>Total Points</span><b class="pink">${total}</b></div>`}
 function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function fixTeamView(){renderManagerSummary()}
 function findFeaturedCard(){const page=document.getElementById('leaguesPage');if(!page)return null;const label=[...page.querySelectorAll('*')].find(el=>el.children.length===0&&(el.textContent||'').trim()==='Featured League');if(!label)return null;let root=label.parentElement;while(root&&root!==page){const controls=[...root.querySelectorAll('button,a,[role="button"]')],hasCopy=controls.some(x=>/copy code/i.test(x.textContent||'')),hasLeave=controls.some(x=>/leave league/i.test(x.textContent||''));if(hasCopy&&hasLeave)return root;root=root.parentElement}return null}
 function beautifyFeaturedLeague(){if(typeof state==='undefined')return;const root=findFeaturedCard();if(!root)return;root.classList.add('fmFeaturedLeagueCard');const txt=root.textContent||'',league=(state.leagues||[]).find(l=>l?.code&&txt.includes(l.code))||(state.leagues||[])[0];if(!league)return;let inner=root.querySelector('.fmFeaturedLeagueInner');if(!inner){const controls=[...root.querySelectorAll('button,a,[role="button"]')],copy=controls.find(x=>/copy code/i.test(x.textContent||'')),leave=controls.find(x=>/leave league/i.test(x.textContent||''));inner=document.createElement('div');inner.className='fmFeaturedLeagueInner';inner.innerHTML='<div class="fmFeaturedMain"><div class="fmFeaturedEyebrow">★ Featured League</div><div class="fmFeaturedName"></div><div class="fmFeaturedMeta"><span class="fmFeaturedCode"></span><span class="fmFeaturedMembers"></span></div></div><div class="fmFeaturedActions"></div>';if(copy)inner.querySelector('.fmFeaturedActions').appendChild(copy);if(leave)inner.querySelector('.fmFeaturedActions').appendChild(leave);const old=[...root.children];root.appendChild(inner);old.forEach(x=>{if(x!==inner)x.style.display='none'})}inner.querySelector('.fmFeaturedName').textContent=league.name||'Mini League';inner.querySelector('.fmFeaturedCode').textContent=league.code||'';const n=(league.members||[]).length;inner.querySelector('.fmFeaturedMembers').textContent=`${n} manager${n===1?'':'s'}`;[...inner.querySelectorAll('button,a,[role="button"]')].forEach(x=>x.classList.add('fmFeaturedAction'))}
 function addStyles(){if(document.getElementById('fmAccountFeatureStyles'))return;const s=document.createElement('style');s.id='fmAccountFeatureStyles';s.textContent=`
 #teamPage.leagueReadOnly .rightPanel,#teamPage.leagueReadOnly .chipsPanel,#teamPage.leagueReadOnly .teamSide{visibility:hidden!important;pointer-events:none!important}
 #teamPage.leagueReadOnly .saveTeam,#teamPage.leagueReadOnly #saveTeam,#teamPage.leagueReadOnly [data-save-team],#teamPage.leagueReadOnly .summary{display:none!important}
 #teamPage.leagueReadOnly .teamGrid,#teamPage.leagueReadOnly .pitchCard,#teamPage.leagueReadOnly .pitch{max-width:revert!important;width:revert!important;margin-left:revert!important;margin-right:revert!important}
 #fmLeagueManagerSummary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));margin:10px 0 12px;border:1px solid rgba(255,255,255,.15);border-radius:10px;background:linear-gradient(180deg,rgba(48,24,83,.97),rgba(35,18,65,.97));overflow:hidden;box-shadow:0 8px 24px rgba(0,0,0,.18)}.fmMgrCell{min-height:72px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:8px 12px}.fmMgrCell+.fmMgrCell{border-left:1px solid rgba(255,255,255,.12)}.fmMgrCell span{font-size:10px;color:#b9afd0;font-weight:800;margin-bottom:5px}.fmMgrCell b{font-size:18px;color:#fff;font-weight:950}.fmMgrCell b.pink,.fmMgrCell em{color:#ff3d9b;font-style:normal}.fmMgrCell em{font-size:13px;margin-left:5px}
 .fmFeaturedLeagueCard{height:auto!important;min-height:0!important;padding:0!important;overflow:hidden!important;border:1px solid rgba(208,174,255,.28)!important;border-radius:18px!important;background:radial-gradient(circle at 15% 0%,rgba(236,54,255,.22),transparent 38%),linear-gradient(135deg,#2b1653 0%,#241348 52%,#32155e 100%)!important;box-shadow:0 18px 44px rgba(4,0,20,.28)!important}.fmFeaturedLeagueInner{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:24px;padding:24px 28px}.fmFeaturedLeagueInner:after{content:'';position:absolute;right:-70px;top:-90px;width:250px;height:250px;border-radius:50%;background:radial-gradient(circle,rgba(255,48,189,.22),transparent 66%);pointer-events:none}.fmFeaturedMain{position:relative;z-index:1}.fmFeaturedEyebrow{font-size:10px;font-weight:950;text-transform:uppercase;letter-spacing:.11em;color:#d3b8ff;margin-bottom:7px}.fmFeaturedName{font-size:25px;line-height:1.05;font-weight:1000;color:#fff;margin-bottom:11px}.fmFeaturedMeta{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.fmFeaturedCode,.fmFeaturedMembers{display:inline-flex;align-items:center;min-height:25px;padding:0 10px;border-radius:999px;font-size:10px;font-weight:900}.fmFeaturedCode{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:#fff;background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.14);letter-spacing:.08em}.fmFeaturedMembers{color:#c9bddf;background:rgba(8,4,28,.25)}.fmFeaturedActions{position:relative;z-index:2;display:flex;align-items:center;gap:9px}.fmFeaturedAction{min-width:112px!important;border-radius:11px!important;padding:11px 16px!important;font-weight:950!important;font-size:11px!important;box-shadow:none!important}.fmFeaturedAction:first-child{background:linear-gradient(90deg,#ff2e8e,#bd45ff)!important;border:0!important;color:#fff!important}.fmFeaturedAction:last-child{background:rgba(9,5,31,.38)!important;border:1px solid rgba(255,255,255,.14)!important;color:#f4efff!important}
 #fmSettingsModal{position:fixed;inset:0;z-index:100000;display:none;place-items:center;background:rgba(4,2,16,.72);backdrop-filter:blur(8px)}#fmSettingsModal.show{display:grid}#fmSettingsCard{width:min(440px,calc(100vw - 30px));padding:22px;border:1px solid rgba(255,255,255,.12);border-radius:20px;background:linear-gradient(180deg,#1a113c,#0e0a27);color:#fff}.fmSetMeta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.fmSetMeta div{padding:11px;border-radius:11px;background:#120c2d}.fmSetMeta small{display:block;color:#8f85a5;font-size:9px}.fmSetRow{display:grid;gap:6px;margin:12px 0}.fmSetRow input{padding:11px;border-radius:10px;border:1px solid #392c61;background:#100b2a;color:#fff}.fmSetActions{display:flex;flex-wrap:wrap;gap:8px}.fmSetBtn{border:0;border-radius:10px;padding:10px 13px;font-weight:900;color:#fff;background:#6f35ff}.fmSetBtn.dark{background:#21183f}.fmSetBtn.danger{background:#a9234e}
 @media(max-width:900px){#fmLeagueManagerSummary{grid-template-columns:1fr 1fr}.fmMgrCell:nth-child(3){border-left:0;border-top:1px solid rgba(255,255,255,.12)}.fmMgrCell:nth-child(4){border-top:1px solid rgba(255,255,255,.12)}.fmFeaturedLeagueInner{grid-template-columns:1fr;padding:20px}.fmFeaturedActions{justify-content:flex-start}}
 `;document.head.appendChild(s)}
 function mountSettings(){if(document.getElementById('accountSettingsBtn'))return;addStyles();const nav=document.querySelector('.snav');if(nav){const b=document.createElement('button');b.id='accountSettingsBtn';b.className='nav';b.innerHTML='<span class="navIcon">⚙</span><span>Settings</span>';b.onclick=e=>{e.preventDefault();openSettings()};nav.appendChild(b)}const m=document.createElement('div');m.id='fmSettingsModal';m.innerHTML='<div id="fmSettingsCard"><h2>Account Settings</h2><div class="fmSetMeta"><div><small>Username</small><b id="fmSetUsername">—</b></div><div><small>Account type</small><b id="fmSetRole">—</b></div></div><div class="fmSetMeta"><div><small>Shared world</small><b id="fmSetWorld">—</b></div><div><small>Join code</small><b id="fmSetCode">—</b></div></div><div class="fmSetRow"><input id="fmSetPassword" type="password" placeholder="New password (6+ characters)"></div><div class="fmSetActions"><button id="fmChangePassword" class="fmSetBtn">Change Password</button><button id="fmLogout" class="fmSetBtn dark">Log Out</button><button id="fmDeleteAccount" class="fmSetBtn danger">Delete Account</button><button id="fmCloseSettings" class="fmSetBtn dark">Close</button></div><div id="fmSetMsg"></div></div>';document.body.appendChild(m);fmCloseSettings.onclick=()=>m.classList.remove('show');fmChangePassword.onclick=changePassword;fmLogout.onclick=async()=>{await client.auth.signOut();location.reload()};fmDeleteAccount.onclick=deleteAccount}
 function openSettings(){mountSettings();const p=FMCloud.getProfile?.(),w=FMCloud.getWorld?.();fmSetUsername.textContent=p?.username||'—';fmSetRole.textContent=p?.role==='creator'?'FPL Creator':'FPL User';fmSetWorld.textContent=w?.name||'—';fmSetCode.textContent=w?.join_code||'—';fmSettingsModal.classList.add('show')}
 async function changePassword(){const pw=fmSetPassword.value;if(pw.length<6)return fmSetMsg.textContent='Password must be at least 6 characters.';const{error}=await client.auth.updateUser({password:pw});fmSetMsg.textContent=error?error.message:'Password changed successfully.'}
 async function deleteAccount(){const p=FMCloud.getProfile?.();if(!confirm(`Delete account ${p?.username||''}? This cannot be undone.`)||!confirm('Final confirmation: permanently delete this account?'))return;const s=await session();const r=await fetch(`${cfg.supabaseUrl}/functions/v1/fmfantasy-delete-account`,{method:'POST',headers:{'Content-Type':'application/json','apikey':cfg.supabaseAnonKey,'Authorization':`Bearer ${s.access_token}`},body:'{}'}),j=await r.json();if(!r.ok||j.error)return fmSetMsg.textContent=j.error||'Could not delete account.';localStorage.clear();location.reload()}
 async function boot(){for(let i=0;i<80&&!FMCloud?.ready?.();i++)await sleep(250);mountSettings();fixTeamView();await syncNews();await syncLeagues();beautifyFeaturedLeague();const b=document.getElementById('viewBanner');if(b)new MutationObserver(()=>{renderManagerSummary()}).observe(b,{attributes:true,subtree:true,childList:true,characterData:true});document.addEventListener('click',e=>{if(e.target.closest('[data-page="leagues"],#createLeague,#confirmCreateLeague,#joinLeague,[data-league],[data-view-manager],[data-leave]'))setTimeout(()=>{syncLeagues();beautifyFeaturedLeague();renderManagerSummary()},300);if(e.target.closest('[data-page="news"]'))setTimeout(syncNews,100);if(e.target.closest('#teamPage'))setTimeout(renderManagerSummary,80)});setInterval(()=>{if(document.getElementById('leaguesPage')?.classList.contains('active')){syncLeagues();beautifyFeaturedLeague()}if(document.getElementById('teamPage')?.classList.contains('active'))renderManagerSummary()},2500)}
 window.addEventListener('fmcloudready',()=>{syncNews();syncLeagues();mountSettings();setTimeout(()=>{beautifyFeaturedLeague();renderManagerSummary()},150)});boot().catch(console.warn)
})();