(()=>{
'use strict';
const VERSION='availability-truth-v8-selected-league-discipline';
const keysInjury=['injured','injury_status','injury','injury_name','injury_type','injury_return_date','expected_return_date','injury_expected_back','injury_end_date','return_date','injured_until','injury_days_remaining'];
const keysSusp=['suspended','suspension_status','suspension_remaining','suspension_games_remaining','ban_games_remaining','banned_until','suspension_until','suspension_detail'];
const clean=v=>String(v??'').trim(),num=v=>Number(v||0)||0,truthy=v=>v===true||String(v).toLowerCase()==='true';
const metaFor=payload=>payload?.meta||(()=>{try{return typeof META!=='undefined'?META:{}}catch(_){return{}}})();
const refDate=payload=>clean(metaFor(payload)?.availability_reference_date||metaFor(payload)?.availability_save_date||metaFor(payload)?.snapshot_date);
const stale=payload=>truthy(metaFor(payload)?.availability_data_stale);
const returnDate=p=>clean(p?.injury_return_date??p?.expected_return_date??p?.injury_expected_back??p?.injury_end_date??p?.injury_evidence?.expected_return);
const suspensionUntil=p=>clean(p?.suspension_evidence_structural?.expiry??p?.banned_until??p?.suspension_until);
function injuryReason(p,payload){if(stale(payload))return'snapshot_stale';const src=clean(p?.injury_evidence?.source),rd=refDate(payload),ret=returnDate(p),days=num(p?.injury_evidence?.days_remaining);if(!src.startsWith('injury_manager.dat/current-window'))return src?'untrusted_injury_source':'no_trusted_injury_source';if(ret&&rd&&ret<=rd)return'injury_return_date_expired';if(!ret&&days<=0)return'no_positive_current_injury_duration';return null}
function suspensionReason(p,payload){if(stale(payload))return'snapshot_stale';const ev=p?.suspension_evidence_structural||{},src=clean(ev.source),rd=refDate(payload),until=suspensionUntil(p),remaining=Math.max(num(p?.suspension_remaining),num(p?.suspension_games_remaining),num(p?.ban_games_remaining),num(ev.games_remaining));const leagueHistory=src==='selected_competition_history_v85'&&clean(ev.competition_scope)==='selected_league_only';const scopedRaw=src==='discipline.dat/active-ban-v1'&&clean(ev.competition_scope)==='selected_league_only';if(!leagueHistory&&!scopedRaw)return src?'untrusted_or_unscoped_suspension_source':'no_trusted_suspension_source';if(remaining<=0)return'no_positive_games_remaining';if(until&&rd&&until<=rd)return'ban_expired';return null}
const injuryValid=(p,payload)=>injuryReason(p,payload)===null,suspensionValid=(p,payload)=>suspensionReason(p,payload)===null;
function snapshot(p,keys){const out={};for(const k of keys)if(p&&p[k]!==undefined&&p[k]!==null&&p[k]!=='')out[k]=p[k];return out}
function clear(p,keys){for(const k of keys)try{delete p[k]}catch(_){}}
function reject(p,kind,reason,raw){p.availability_rejected_evidence=p.availability_rejected_evidence||{};p.availability_rejected_evidence[kind]={reason,raw,observed_at_runtime:VERSION}}
function sanitizePayload(payload){if(!payload||!Array.isArray(payload.players))return payload;let injuries=0,suspensions=0,suppressedInjuries=0,suppressedSuspensions=0;for(const p of payload.players){const ir=injuryReason(p,payload);if(ir===null){injuries++;p.injured=true;p.injury_status='Injured'}else{const raw=snapshot(p,keysInjury),has=!!(p?.injury_evidence||Object.keys(raw).length);if(has){suppressedInjuries++;reject(p,'injury',ir,{...raw,injury_evidence:p.injury_evidence??null})}clear(p,keysInjury)}const sr=suspensionReason(p,payload);if(sr===null){suspensions++;p.suspended=true;p.suspension_status='Suspended'}else{const raw=snapshot(p,keysSusp),has=!!(p?.suspension_evidence||p?.suspension_evidence_structural||Object.keys(raw).length);if(has){suppressedSuspensions++;reject(p,'suspension',sr,{...raw,suspension_evidence:p.suspension_evidence??null,suspension_evidence_structural:p.suspension_evidence_structural??null})}clear(p,keysSusp)}}payload.meta=payload.meta||{};payload.meta.injured_players=injuries;payload.meta.suspended_players=suspensions;payload.meta.availability_truth_policy='injuries require current injury_manager evidence; league suspensions require selected-league history or explicitly competition-scoped current-ban evidence';payload.meta.availability_truth_runtime={version:VERSION,reference_date:refDate(payload)||null,data_stale:stale(payload),injuries,suspensions,suppressed_injuries:suppressedInjuries,suppressed_suspensions:suppressedSuspensions};return payload}
function fmt(v){if(!v)return'';try{const d=new Date(String(v).length<=10?String(v)+'T12:00:00':v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}catch(_){return String(v)}}
function activeInjuries(payload){sanitizePayload(payload);const out=[];for(const p of payload?.players||[]){if(!injuryValid(p,payload))continue;const ret=returnDate(p);out.push({pid:String(p.pid),name:(typeof playerName==='function'?playerName(p):p.name),club:p.club,pos:p.pos,detail:`Injured${ret?` · expected back ${fmt(ret)}`:''}`})}return out}
function activeSuspensions(payload){sanitizePayload(payload);const out=[];for(const p of payload?.players||[]){if(!suspensionValid(p,payload))continue;const remaining=Math.max(num(p?.suspension_remaining),num(p?.suspension_games_remaining),num(p?.ban_games_remaining),num(p?.suspension_evidence_structural?.games_remaining)),until=suspensionUntil(p);out.push({pid:String(p.pid),name:(typeof playerName==='function'?playerName(p):p.name),club:p.club,pos:p.pos,detail:`Suspended · ${remaining} league match${remaining===1?'':'es'} remaining${until?` · until ${fmt(until)}`:''}`})}return out}
function install(){try{globalThis.fmInferActiveInjuries=activeInjuries;globalThis.fmInferActiveSuspensions=activeSuspensions}catch(_){ }const payload=window.FMCloud?.getWorld?.()?.payload||null;if(payload)sanitizePayload(payload);try{if(typeof PLAYERS!=='undefined'&&Array.isArray(PLAYERS))sanitizePayload({players:PLAYERS,meta:metaFor(payload)})}catch(_){ }try{if(typeof renderAll==='function')renderAll();else if(typeof renderNews==='function')renderNews()}catch(_){ }}
window.FMAvailabilityTruth={version:VERSION,sanitizePayload,injuryValid,suspensionValid,injuryReason,suspensionReason,activeInjuries,activeSuspensions};window.addEventListener('fmcloudready',()=>setTimeout(install,0));window.addEventListener('focus',()=>setTimeout(install,0));setTimeout(install,1000);
})();
