(()=>{
'use strict';
const arr=v=>Array.isArray(v)?v:[];
const nonempty=v=>v!==null&&v!==undefined&&String(v).trim()!=='';
const norm=v=>String(v??'').trim().toLocaleLowerCase();
function g(name,fallback){try{return typeof window[name]!=='undefined'?window[name]:fallback}catch(_){return fallback}}
function stablePersonId(p){if(!p)return null;for(const k of ['pid','player_id','person_id','uid'])if(nonempty(p[k]))return String(p[k]);if(nonempty(p.id)){const m=String(p.id).match(/^(-?\d+)/);if(m)return m[1]}return null}
function clubOf(p){const label=p?.club??p?.club_name??p?.team??p?.team_name??null,id=nonempty(p?.club_id)?Number(p.club_id):null;return{id:Number.isFinite(id)?id:null,label:nonempty(label)?String(label):null,label_key:nonempty(label)?norm(label):null}}
function calendar(fixtures){const ids=new Set(),names=new Set();for(const f of fixtures){for(const k of ['home_id','away_id'])if(nonempty(f?.[k])&&Number.isFinite(Number(f[k])))ids.add(Number(f[k]));if(nonempty(f?.home))names.add(norm(f.home));if(nonempty(f?.away))names.add(norm(f.away))}return{ids,names}}
function decodedShift(){const meta=g('META',{})||{};for(const k of ['fixture_to_club_shift','fixture_club_shift','team_to_club_shift']){const n=Number(meta[k]);if(Number.isFinite(n)&&n!==0)return {value:n,source:`META.${k}`}}return null}
function shiftedMembership(c,cal,shift){if(!c||!Number.isFinite(c.id)||!shift||!cal.ids.size)return{current:false,method:'shift_unavailable',translated_id:null};const plus=c.id+shift.value,minus=c.id-shift.value,plusHit=cal.ids.has(plus),minusHit=cal.ids.has(minus);if(plusHit!==minusHit)return{current:true,method:plusHit?'club_id_plus_decoded_shift':'club_id_minus_decoded_shift',translated_id:plusHit?plus:minus};if(plusHit&&minusHit)return{current:false,method:'decoded_shift_ambiguous',translated_id:null};return{current:false,method:'decoded_shift_miss',translated_id:null}}
function build(){
 const players=arr(g('PLAYERS',[])).filter(p=>p&&p.visible!==false),fixtures=arr(g('SEASON_FIXTURES',[])),cal=calendar(fixtures),shift=decodedShift();
 const prior=g('FM_CURRENT_SQUAD_IDENTITY_EVIDENCE_V2',null)||g('FM_CURRENT_SQUAD_IDENTITY_EVIDENCE',null);
 const byPerson=new Map();let shiftValidated=0,shiftAmbiguous=0,shiftMiss=0,nameAgreement=0,nameConflict=0;
 for(const p of players){const pid=stablePersonId(p);if(!pid)continue;const c=clubOf(p);let direct=Number.isFinite(c.id)&&cal.ids.has(c.id),name=!!(c.label_key&&cal.names.has(c.label_key)),sm=shiftedMembership(c,cal,shift);if(sm.method==='decoded_shift_ambiguous')shiftAmbiguous++;if(sm.method==='decoded_shift_miss')shiftMiss++;if(sm.current){shiftValidated++;if(name)nameAgreement++;else if(c.label_key&&cal.names.size)nameConflict++;}const row={record_id:p.id??null,pid,club:c,direct_id_match:direct,name_match:name,shift_match:sm.current,shift_method:sm.method,translated_fixture_team_id:sm.translated_id};if(!byPerson.has(pid))byPerson.set(pid,[]);byPerson.get(pid).push(row)}
 let rescuedUnique=0,rescuedAmbiguous=0;const rescued={},conflicts=[];
 for(const [pid,rows] of byPerson){const priorUnique=prior?.current_membership?.unique_by_person?.[pid]||null;if(priorUnique)continue;const hits=rows.filter(r=>r.shift_match);const keys=new Map();for(const r of hits){const key=r.translated_fixture_team_id!=null?`fixture_id:${r.translated_fixture_team_id}`:r.club.label_key?`name:${r.club.label_key}`:null;if(key)keys.set(key,r)}if(keys.size===1){rescuedUnique++;const [key,row]=[...keys.entries()][0];rescued[pid]={club_kind:key.startsWith('fixture_id:')?'translated_fixture_id':'name',club_key:key.slice(key.indexOf(':')+1),club_label:row.club.label,decoded_shift:shift?.value??null,shift_source:shift?.source??null,records:hits.length,membership_methods:[...new Set(hits.map(x=>x.shift_method))]}}else if(keys.size>1){rescuedAmbiguous++;if(conflicts.length<50)conflicts.push({pid,clubs:[...keys.values()].map(r=>r.club.label),translated_fixture_team_ids:[...keys.values()].map(r=>r.translated_fixture_team_id)})}}
 const evidence={version:1,generated_from_existing_import_pass:true,no_additional_fm_scan:true,policy:'Reuse a decoded fixture-team↔club entity shift only as an additional current-squad identity path. Direct ID and exact calendar-name strategies remain intact. A shifted ID is accepted only when exactly one direction lands in the current decoded calendar; bidirectional hits stay ambiguous.',decoded_shift:shift,population:{visible_player_records:players.length,calendar_team_ids:cal.ids.size,stable_persons:byPerson.size},shift_evidence:{records_validated_by_shift:shiftValidated,shift_ambiguous_records:shiftAmbiguous,shift_miss_records:shiftMiss,shift_matches_with_calendar_name_agreement:nameAgreement,shift_matches_without_calendar_name_agreement:nameConflict},rescued_membership:{unique_persons:rescuedUnique,ambiguous_persons:rescuedAmbiguous,unique_by_person:rescued,conflict_examples:conflicts}};
 try{window.FM_CURRENT_SQUAD_ENTITY_SHIFT_EVIDENCE=evidence;window.fmCurrentSquadShiftIdentityForPerson=pid=>evidence.rescued_membership.unique_by_person[String(pid)]||null}catch(_){}
 try{const cap=window.FM_IMPORT_CAPABILITIES;if(cap&&typeof cap==='object'){cap.current_squad_entity_shift_evidence=evidence;const current=cap.current_squad_identity&&typeof cap.current_squad_identity==='object'?cap.current_squad_identity:null;if(current&&rescuedUnique){current.shift_rescued_unique_persons=rescuedUnique;current.shift_rescued_by_person=rescued}const gaps=Array.isArray(cap.unresolved_capabilities)?cap.unresolved_capabilities:[];if(shift&&shiftValidated===0&&!gaps.includes('decoded_fixture_club_shift_membership_validation'))gaps.push('decoded_fixture_club_shift_membership_validation');cap.unresolved_capabilities=gaps}}catch(_){}
 try{if(typeof FM_DEBUG!=='undefined'&&FM_DEBUG){FM_DEBUG.currentSquadEntityShiftEvidence=evidence;FM_DEBUG.currentSquadEntityShiftSummary={decoded_shift:shift?.value??null,shift_source:shift?.source??null,records_validated_by_shift:shiftValidated,rescued_unique_persons:rescuedUnique,rescued_ambiguous_persons:rescuedAmbiguous,name_agreement:nameAgreement,name_conflict:nameConflict}}}catch(_){}
 return evidence;
}
function install(){let original;try{original=typeof applyImportedPayload==='function'?applyImportedPayload:null}catch(_){original=null}if(original&&!original.__fmCurrentSquadEntityShiftWrapped){const wrapped=function(...args){const out=original.apply(this,args);try{build()}catch(e){console.warn('Current squad entity-shift evidence failed',e)}return out};wrapped.__fmCurrentSquadEntityShiftWrapped=true;try{applyImportedPayload=wrapped}catch(_){}}try{build()}catch(_){}}
window.fmBuildCurrentSquadEntityShiftEvidence=build;install();
})();
