(()=>{
'use strict';
const VERSION='import-model-v85-partial-history-pricing-league-discipline';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v||0)||0));
const num=v=>Number(v||0)||0;
const arr=v=>Array.isArray(v)?v:[];
const norm=v=>String(v??'').trim().toLowerCase();
const roundHalf=v=>Math.round((Number(v)||0)*2)/2;
const posBase=pos=>({GK:4,DEF:4,MID:4.5,FWD:4.5}[pos]??4.5);
function partialHistory(payload){const m=payload?.meta||{},played=num(m.played_results),rich=num(m.rich_matches);return norm(m.history_coverage_status)==='partial'||num(m.rich_matches_missing)>0||(played>0&&rich>0&&rich<played*.95)}
function currentUnavailable(p){const t=[p?.injury_status,p?.suspension_status,p?.status].filter(Boolean).join(' ').toLowerCase();return !!(p?.injured||p?.suspended||t.includes('injur')||t.includes('suspend')||p?.return_date||p?.injury_return_date||p?.injury_evidence)}
function leagueSuspensions(payload){
 const players=arr(payload?.players),fixtures=arr(payload?.fixtures);const fields=['suspended','suspension_status','suspension_remaining','suspension_games_remaining','ban_games_remaining','banned_until','suspension_until','suspension_detail','suspension_evidence','suspension_evidence_structural'];
 const played=new Map(),future=new Map();
 const push=(map,club,date)=>{if(!club||!date)return;const a=map.get(club)||[];a.push(String(date).slice(0,10));map.set(club,a)};
 for(const f of fixtures){const date=String(f?.date||'').slice(0,10);if(!date)continue;for(const club of [f?.home,f?.away])push(String(f?.status||'')==='played'?played:future,club,date)}
 for(const m of [played,future])for(const a of m.values())a.sort();
 let suspended=0,redTriggers=0,yellowTriggers=0;
 for(const p of players){for(const k of fields)delete p[k];let red=null,yellow=null,ycTotal=0;const hist=[...arr(p?.history)].sort((a,b)=>String(a?.date||'').localeCompare(String(b?.date||''))||num(a?.gameweek)-num(b?.gameweek));
   for(const h of hist){const date=String(h?.date||'').slice(0,10);if(!date)continue;const rc=num(h?.rc),yc=Math.max(0,num(h?.yc));if(rc>0){red={date,gw:num(h?.gameweek),reason:'league red card'};redTriggers++;continue}const prev=ycTotal;ycTotal+=yc;if(yc>0&&Math.floor(ycTotal/5)>Math.floor(prev/5)){yellow={date,gw:num(h?.gameweek),reason:'league yellow-card threshold'};yellowTriggers++}}
   const trigger=[red,yellow].filter(Boolean).sort((a,b)=>a.date.localeCompare(b.date)||a.gw-b.gw).pop();if(!trigger)continue;const club=p?.club;if(club&&(played.get(club)||[]).some(d=>d>trigger.date))continue;const next=(future.get(club)||[]).find(d=>d>trigger.date)||null;
   p.suspended=true;p.suspension_status='suspended';p.suspension_remaining=1;p.suspension_games_remaining=1;p.ban_games_remaining=1;p.suspension_detail='1 league match';if(next){p.banned_until=next;p.suspension_until=next}p.suspension_evidence_structural={source:'selected_competition_history_v85',competition_scope:'selected_league_only',trigger_date:trigger.date,trigger_gameweek:trigger.gw,reason:trigger.reason,games_remaining:1,expiry:next};suspended++;
 }
 payload.meta=payload.meta||{};payload.meta.suspended_players=suspended;payload.meta.suspension_truth_policy='selected competition history + selected competition fixtures only v85';payload.meta.suspension_decoder={version:VERSION,source:'selected_competition_history_v85',raw_discipline_policy:'diagnostic_only_not_used_for_league_suspension',red_triggers_seen:redTriggers,yellow_threshold_triggers_seen:yellowTriggers,suspended_players:suspended};return payload;
}
function seasonReprice(payload){
 const players=arr(payload?.players),fixtures=arr(payload?.fixtures),partial=partialHistory(payload);const clubGames=new Map();for(const f of fixtures){if(String(f?.status||'')!=='played')continue;for(const club of [f?.home,f?.away])if(club)clubGames.set(club,(clubGames.get(club)||0)+1)}
 const raws=new Map();
 for(const p of players){const pos=String(p?.pos||'');if(!['GK','DEF','MID','FWD'].includes(pos))continue;const c=p.price_context||(p.price_context={}),q=clamp(c.quality),d=clamp(c.depth_score),team=clamp(c.team_strength),attack=clamp(c.attack_profile),mins=Math.max(0,num(p.minutes)),starts=Math.max(0,num(p.starts)),hist=arr(p.history),decoded=hist.length,games=clubGames.get(p.club)||num(c.club_played_matches)||num(c.observed_matches),available=Math.max(0,num(c.available_matches)||games);let roleGames=(partial&&decoded>0)?decoded:Math.max(0,available);let share=roleGames?clamp(mins/(90*roleGames)):0,startShare=roleGames?clamp(starts/roleGames):0;const unavailable=currentUnavailable(p),expected=!!(unavailable&&mins<=0&&(q>=.55||d>=.55||num(p.ca)>=130));let nailed=roleGames?clamp(.86*(.66*share+.34*startShare)+.14*d):d;if(expected)nailed=Math.max(.68,d*.8);
   let raw,availability;if(games>=2&&mins===0&&!expected&&!partial){raw=Math.min(4.5,3.5+.42*q+.2*d);availability='No minutes · basement price'}else{availability=partial?(decoded?'Selected-league retained role evidence':'Current squad / ability projection · retained league detail missing'):(games>=2?'Observed role':'Pre-season projection');if(pos==='GK')raw=Math.min(5.5,3.70+.30*q+.78*nailed+.82*team);else if(pos==='DEF')raw=3.60+.48*q+.92*nailed+.78*attack+1.42*team+.18*(q**4);else if(pos==='MID'&&attack<.34)raw=Math.min(6.8,4.10+.48*q+1.00*nailed+.26*attack+.72*team+.12*(q**3));else if(pos==='MID'){raw=4.10+.72*q+1.18*nailed+1.70*attack+.82*team+4.15*(q**4)*(.30+.70*nailed)*(.40+.60*attack);if(q>=.94&&nailed>=.82&&attack>=.72&&team>=.65)raw+=.8;raw=Math.min(15,raw)}else{raw=4.10+.76*q+1.28*nailed+1.22*attack+.92*team+3.85*(q**4)*(.24+.76*nailed);if(q>=.95&&nailed>=.82&&team>=.58)raw+=.6;raw=Math.min(14.5,raw)}}
   if(roleGames>=3&&!expected){if(share<.15){raw=Math.min(raw,{GK:4,DEF:4.5,MID:4.5,FWD:5}[pos]);availability='Rarely used backup'}else if(share<.35){raw=Math.min(raw,{GK:4.5,DEF:5,MID:5.2,FWD:5.5}[pos]);availability='Backup / rotation'}else if(share<.55){raw-=.35;availability='Rotation / partial starter'}}
   if(games>=3){if(pos==='FWD'){if(team<.28)raw=Math.min(raw,6);else if(team<.45)raw=Math.min(raw,6.5);else if(team<.58)raw=Math.min(raw,7)}else if(pos==='DEF'){if(team<.28)raw=Math.min(raw,4.7);else if(team<.42)raw=Math.min(raw,5.2)}else if(pos==='MID'&&attack<.45&&team<.45)raw=Math.min(raw,5.5)}
   c.quality=Number(q.toFixed(3));c.depth_score=Number(d.toFixed(3));c.team_strength=Number(team.toFixed(3));c.attack_profile=Number(attack.toFixed(3));c.nailedness=Number(nailed.toFixed(3));c.minutes_share=Number(share.toFixed(3));c.start_share=Number(startShare.toFixed(3));c.observed_matches=roleGames;c.club_played_matches=games;c.history_coverage_partial=partial;c.decoded_selected_competition_rows=decoded;c.availability_signal=availability;c.zero_minute_exception=expected;c.current_unavailable=unavailable;c.established_absence=expected;raws.set(String(p.pid??p.id),raw)
 }
 const byPos={GK:[],DEF:[],MID:[],FWD:[]};for(const p of players)if(byPos[p?.pos]&&raws.has(String(p.pid??p.id)))byPos[p.pos].push(p);for(const pos of Object.keys(byPos))byPos[pos].sort((a,b)=>raws.get(String(b.pid??b.id))-raws.get(String(a.pid??a.id)));
 for(const pos of Object.keys(byPos)){for(let i=0;i<byPos[pos].length;i++){const p=byPos[pos][i],id=String(p.pid??p.id),c=p.price_context||{},q=clamp(c.quality),team=clamp(c.team_strength),att=clamp(c.attack_profile),nailed=clamp(c.nailedness),obs=Math.max(0,num(c.observed_matches)),minuteShare=obs?clamp(num(p.minutes)/(obs*90)):0,startRate=obs?clamp(num(p.starts)/obs):0;let raw=raws.get(id);c.position_price_rank=i+1;c.observed_minute_share=Number(minuteShare.toFixed(3));c.selected_competition_start_rate=Number(startRate.toFixed(3));const unavailable=currentUnavailable(p),absence=!!(unavailable&&num(p.minutes)<=0&&(q>=.55||clamp(c.depth_score)>=.55||num(p.ca)>=130));c.current_unavailable=unavailable;c.established_absence=absence;
     if(num(p.minutes)===0&&obs>=2&&!partial&&!c.zero_minute_exception)raw=Math.min(raw,{GK:4,DEF:4.5,MID:4.5,FWD:5}[pos]);else if(num(p.minutes)===0&&c.zero_minute_exception){raw=Math.max({GK:4.5,DEF:5,MID:5.5,FWD:6}[pos],Math.min(raw,{GK:5,DEF:5.5,MID:7,FWD:7.5}[pos]))}else if(pos==='GK')raw=Math.min(raw,i<2?5.5:i<8?5:4.5);else if(pos==='DEF'){if(att<.42){const cap=i<3&&team>=.78&&nailed>=.84?6:i<18?5.5:i<60?5:4.5;raw=Math.min(raw,cap)}else if(i===0&&team>=.70&&att>=.58)raw=Math.min(7.5,raw+.35);else if(i<3&&team>=.58)raw=Math.min(raw,6.5);else if(i<6)raw=Math.min(raw,6);else if(i<18)raw=Math.min(raw,5.5);else if(i<60)raw=Math.min(raw,5);else raw=Math.min(raw,4.5)}else if(pos==='MID'){if(att<.34){const cap=i<8&&q>=.88&&team>=.62&&nailed>=.80?6:i<45?5.5:5;raw=Math.min(raw,cap)}else{const cap=i<2?15:i<5?12.5:i<10?10.5:i<20?9:i<40?8:i<80?7:i<140?6.5:6;raw=Math.min(raw,cap)}}else{const cap=i<2?14:i<5?11.5:i<10?9.5:i<20?8:i<40?7.5:i<80?7:6.5;raw=Math.min(raw,cap)}
     let role='projected',floor=posBase(pos),cap=15;if(absence){role='established_absence';floor={GK:4.5,DEF:5,MID:5.5,FWD:6}[pos];cap={GK:5,DEF:5.5,MID:7,FWD:7.5}[pos]}else if(obs>=2){if(minuteShare<.20&&startRate<.10){role='backup';floor={GK:4,DEF:4,MID:4.5,FWD:4.5}[pos];cap={GK:4,DEF:4.5,MID:5,FWD:5.5}[pos]}else if(startRate>=.60||minuteShare>=.70){role='starter';floor={GK:4.5,DEF:5,MID:5.5,FWD:6}[pos];cap={GK:6,DEF:8,MID:15,FWD:14}[pos]}else if(startRate>=.30||minuteShare>=.45){role='squad';floor={GK:4.5,DEF:4.5,MID:5,FWD:5.5}[pos];cap={GK:5,DEF:6,MID:9,FWD:9.5}[pos]}else{role='rotation';floor={GK:4,DEF:4.5,MID:4.5,FWD:5}[pos];cap={GK:4.5,DEF:5.5,MID:7,FWD:7.5}[pos]}}raw=Math.max(floor,Math.min(raw,cap));const price=roundHalf(Math.max(posBase(pos),raw));p.price=price;p.model_price=price;p.launch_price=price;p.dynamic_price=price;p.price_change_history=[];p.price_baseline_gw=num(payload?.meta?.latest_gameweek_with_result);c.usage_role=role;c.usage_role_floor=floor;c.usage_role_cap=cap;c.distribution_cap=Number(raw.toFixed(2));c.price=price;c.pricing_model_version=VERSION;c.summary=`${c.role||'Player'} · selected-league minute share ${Math.round(minuteShare*100)}% · starts ${Math.round(startRate*100)}% · attack ${Math.round(att*100)}/100 · team strength ${Math.round(team*100)}/100 · quality ${Math.round(q*100)}/100 · ${c.availability_signal||''}`;
   }}
 payload.meta=payload.meta||{};payload.meta.pricing_model='fpl-shaped-v85-partial-history-role-confidence';payload.meta.pricing_role_evidence_policy='partial history uses only decoded selected-league rows; missing retained matches are unknown, never automatic bench games';payload.meta.price_policy='launch price frozen at database import; only post-import sustained form can move price';payload.meta.price_baseline_gw=num(payload.meta.latest_gameweek_with_result);payload.meta.import_model_finalizer=VERSION;return payload;
}
function transform(payload){if(!payload||!Array.isArray(payload.players))return payload;leagueSuspensions(payload);let mode='';try{mode=norm(window.__FM_IMPORT_MODE_ACTIVE||'')}catch(_e){}if(mode==='season')seasonReprice(payload);return payload}
function install(){let original;try{original=globalThis.fmApplyPostPayloadPricingCorrections}catch(_e){return false}if(typeof original!=='function'||original.__fmV85Wrapped)return false;const wrapped=function(payload,...args){const out=original(payload,...args);transform(payload);try{if(typeof FM_DEBUG!=='undefined')FM_DEBUG.lastMeta=payload?.meta||null;if(typeof fmDebugAdd==='function')fmDebugAdd('info','V85 importer pricing/competition-discipline finaliser applied.',{pricing_model:payload?.meta?.pricing_model,suspension_policy:payload?.meta?.suspension_truth_policy,suspended_players:payload?.meta?.suspended_players})}catch(_e){}return out};wrapped.__fmV85Wrapped=true;wrapped.__fmV85Original=original;globalThis.fmApplyPostPayloadPricingCorrections=wrapped;return true}
window.FMImportModelV85={version:VERSION,transform,seasonReprice,leagueSuspensions,install};let tries=0;const timer=setInterval(()=>{tries++;if(install()||tries>50)clearInterval(timer)},100);window.addEventListener('fmcloudready',install);
})();
