(()=>{
'use strict';
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const low=v=>clean(v).toLocaleLowerCase();
function components(p){const e=p?.name_component_evidence&&typeof p.name_component_evidence==='object'?p.name_component_evidence:{};return{legal:clean(p.legal_name||p.legal_full_name||p.full_name||e.legal_full||e.legal_name),first:clean(p.first_name||p.forename||e.first||e.first_name),surname:clean(p.surname_name||p.football_surname||p.surname||p.family_name||p.last_name||e.surname_family||e.surname_name),common:clean(p.common_name||p.known_as||p.preferred_name||e.common_known_as||e.common_name),display:clean(p.public_name||p.canonical_display_name||p.football_display_name||p.display_name||p.name||e.resolved_display_name),nickname:clean(p.nickname||e.nickname),shirt:clean(p.shirt_name||e.shirt_name),short:clean(p.preferred_short_name||e.preferred_short_name),pools:e.component_pool_ids||{}}}
function inspect(p){const c=components(p),d=low(c.display),common=low(c.common),surname=low(c.surname),legal=low(c.legal);let suffix='';if(c.common&&d.startsWith(common+' '))suffix=clean(c.display.slice(c.common.length));const rel={display_exact_common_surname:!!c.common&&!!c.surname&&d===low(`${c.common} ${c.surname}`),display_starts_with_common:!!c.common&&d.startsWith(common+' '),display_suffix_after_common:suffix||null,surname_exactly_matches_display_suffix:!!suffix&&!!c.surname&&low(suffix)===surname,legal_contains_common:!!c.common&&!!c.legal&&legal.includes(common),legal_contains_surname:!!c.surname&&!!c.legal&&legal.includes(surname),common_is_not_first_name:!!c.common&&!!c.first&&common!==low(c.first),display_not_legal:!!c.display&&!!c.legal&&d!==legal};const confidence=rel.display_exact_common_surname&&rel.surname_exactly_matches_display_suffix?'validated_common_plus_football_surname':rel.display_starts_with_common&&rel.surname_exactly_matches_display_suffix?'validated_suffix_relationship':rel.display_starts_with_common?'common_prefix_only':'unresolved';return{components:c,relationship:rel,confidence,display_override_applied:false}}
function run(){let players=[];try{players=Array.isArray(PLAYERS)?PLAYERS:[]}catch(_){}const stats={players:0,with_common:0,with_surname:0,common_prefix:0,validated_common_plus_surname:0,validated_suffix_relationship:0,common_differs_from_first:0,taty_probe:null,examples:[]};for(const p of players){if(!p||p.visible===false)continue;const ev=inspect(p);p.name_schema_evidence=ev;stats.players++;if(ev.components.common)stats.with_common++;if(ev.components.surname)stats.with_surname++;if(ev.relationship.display_starts_with_common)stats.common_prefix++;if(ev.relationship.display_exact_common_surname)stats.validated_common_plus_surname++;if(ev.relationship.surname_exactly_matches_display_suffix)stats.validated_suffix_relationship++;if(ev.relationship.common_is_not_first_name)stats.common_differs_from_first++;if(stats.examples.length<12&&ev.confidence.startsWith('validated_'))stats.examples.push({id:p.id??p.player_id??null,display:ev.components.display,common:ev.components.common,surname:ev.components.surname,legal:ev.components.legal||null,confidence:ev.confidence,pools:ev.components.pools});const isTaty=String(p.id??p.player_id??'')==='24517'||low(ev.components.display)==='taty castellanos';if(isTaty)stats.taty_probe={id:p.id??p.player_id??null,display:ev.components.display,legal:ev.components.legal||null,first:ev.components.first||null,common:ev.components.common||null,surname:ev.components.surname||null,display_suffix_after_common:ev.relationship.display_suffix_after_common,common_plus_surname_validated:ev.relationship.display_exact_common_surname&&ev.relationship.surname_exactly_matches_display_suffix,rejects_common_only:low(ev.components.display)!==low(ev.components.common),rejects_legal_when_different:!ev.components.legal||low(ev.components.display)!==low(ev.components.legal)||low(ev.components.legal)==='taty castellanos',validation_probe_only_no_display_override:true,pools:ev.components.pools};}
 try{window.FM_NAME_SCHEMA_EVIDENCE=stats;if(typeof FM_DEBUG!=='undefined'&&FM_DEBUG){FM_DEBUG.nameSchemaEvidence=stats;FM_DEBUG.nameSchemaPolicy='Learn common/known-as + football-surname relationships only when the independently resolved FM display validates them. Never truncate a legal name or force common-name-only output.'}}catch(_){}
 return stats}
function install(){let original;try{original=typeof applyImportedPayload==='function'?applyImportedPayload:null}catch(_){original=null}if(original&&!original.__fmNameEvidenceLearningWrapped){const wrapped=function(...args){const out=original.apply(this,args);try{if(typeof window.fmAnnotateImporterEvidence==='function')window.fmAnnotateImporterEvidence();run();if(typeof window.fmBuildImportCapabilities==='function')window.fmBuildImportCapabilities()}catch(e){console.warn('Name schema evidence learning failed',e)}return out};wrapped.__fmNameEvidenceLearningWrapped=true;try{applyImportedPayload=wrapped}catch(_){}}try{run()}catch(_){}}
window.fmLearnNameSchemaEvidence=run;install();
})();
