(()=>{
'use strict';
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const low=v=>clean(v).toLocaleLowerCase();
function stablePersonId(p){const direct=p?.pid??p?.player_id??p?.person_id??p?.uid??null;if(direct!==null&&direct!==undefined&&String(direct).trim()!=='')return String(direct).trim();const raw=String(p?.id??'').trim();const m=raw.match(/^(\d+)(?:\||$)/);return m?m[1]:raw||null}
function components(p){const e=p?.name_component_evidence&&typeof p.name_component_evidence==='object'?p.name_component_evidence:{};return{legal:clean(p.legal_full||p.legal_name||p.legal_full_name||p.full_name||e.legal_full||e.legal_name),first:clean(p.first||p.first_name||p.forename||e.first||e.first_name),surname:clean(p.surname_family||p.surname_name||p.football_surname||p.surname||p.family_name||p.last_name||e.surname_family||e.surname_name),common:clean(p.common_known_as||p.common_name||p.known_as||p.preferred_name||e.common_known_as||e.common_name),display:clean(p.public_name||p.canonical_display_name||p.football_display_name||p.display_name||p.name||e.resolved_display_name),nickname:clean(p.nickname||e.nickname),shirt:clean(p.shirt_name||e.shirt_name),short:clean(p.preferred_short_name||e.preferred_short_name),pools:e.component_pool_ids||{first:p.first_pool_id??null,surname:p.surname_pool_id??null,common:p.common_pool_id??null}}}

// Retained match rows are a genuinely separate FM representation from the person/player record.
// Learn their public-name aliases by stable person ID, but never let a single noisy row rewrite a name.
function retainedAliasEvidence(){
 const out=new Map(),seen=new WeakSet();let matches=[];try{matches=Array.isArray(MATCHES)?MATCHES:[]}catch(_){}
 const add=(id,name)=>{id=clean(id);name=clean(name);if(!id||!name||/^player id \d+$/i.test(name))return;let c=out.get(id);if(!c){c=new Map();out.set(id,c)}c.set(name,(c.get(name)||0)+1)};
 const walk=(v,depth=0)=>{if(!v||depth>4)return;if(Array.isArray(v)){for(const x of v)walk(x,depth+1);return}if(typeof v!=='object')return;if(seen.has(v))return;seen.add(v);
   const explicit=v.pid??v.player_id??v.person_id??v.uid??null;
   if(explicit!==null&&explicit!==undefined){const nm=v.player_name??v.player??v.public_name??v.display_name??v.name??null;add(explicit,nm)}
   for(const [k,x] of Object.entries(v)){if(k==='raw'||k==='bytes'||k==='debug')continue;if(Array.isArray(x)||(x&&typeof x==='object'))walk(x,depth+1)}
 };
 for(const m of matches)walk(m,0);return out;
}
function consensusAlias(counts){if(!counts||!counts.size)return null;const arr=[...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));const top=arr[0],second=arr[1];const total=arr.reduce((s,x)=>s+x[1],0);const unopposed=!second;const strong=top[1]>=2&&(unopposed||top[1]-second[1]>=2||top[1]/Math.max(1,total)>=0.75);return{name:top[0],count:top[1],total,alternatives:arr.slice(1,5).map(([name,count])=>({name,count})),strong}}
function inspect(p,aliasMap){const c=components(p),d=low(c.display),common=low(c.common),surname=low(c.surname),legal=low(c.legal),personId=stablePersonId(p);let suffix='';if(c.common&&d.startsWith(common+' '))suffix=clean(c.display.slice(c.common.length));const retained=consensusAlias(personId?aliasMap.get(personId):null);const commonSurname=c.common&&c.surname&&common!==surname?`${c.common} ${c.surname}`:'';const rel={display_exact_common_surname:!!commonSurname&&d===low(commonSurname),display_starts_with_common:!!c.common&&d.startsWith(common+' '),display_suffix_after_common:suffix||null,surname_exactly_matches_display_suffix:!!suffix&&!!c.surname&&low(suffix)===surname,legal_contains_common:!!c.common&&!!c.legal&&legal.includes(common),legal_contains_surname:!!c.surname&&!!c.legal&&legal.includes(surname),common_is_not_first_name:!!c.common&&!!c.first&&common!==low(c.first),display_not_legal:!!c.display&&!!c.legal&&d!==legal,retained_alias_matches_display:!!retained&&!!c.display&&low(retained.name)===d,retained_alias_matches_common_surname:!!retained&&!!commonSurname&&low(retained.name)===low(commonSurname)};const crossValidated=!!retained?.strong&&rel.retained_alias_matches_common_surname;let confidence=crossValidated?'cross_source_validated_common_plus_football_surname':rel.display_exact_common_surname&&rel.surname_exactly_matches_display_suffix?'validated_common_plus_football_surname':rel.display_starts_with_common&&rel.surname_exactly_matches_display_suffix?'validated_suffix_relationship':rel.display_starts_with_common?'common_prefix_only':'unresolved';return{person_id:personId,components:c,relationship:rel,retained_match_alias:retained,cross_source_common_plus_surname_validated:crossValidated,recommended_natural_display_name:crossValidated?retained.name:null,confidence,display_override_applied:false}}
function run(){let players=[];try{players=Array.isArray(PLAYERS)?PLAYERS:[]}catch(_){}const aliases=retainedAliasEvidence();const stats={version:3,players:0,with_stable_person_id:0,with_common:0,with_surname:0,common_prefix:0,validated_common_plus_surname:0,validated_suffix_relationship:0,cross_source_common_surname_validated:0,retained_alias_persons:aliases.size,retained_consensus_recommended:0,common_differs_from_first:0,taty_probe:null,examples:[]};for(const p of players){if(!p||p.visible===false)continue;const ev=inspect(p,aliases);p.name_schema_evidence=ev;stats.players++;if(ev.person_id)stats.with_stable_person_id++;if(ev.components.common)stats.with_common++;if(ev.components.surname)stats.with_surname++;if(ev.relationship.display_starts_with_common)stats.common_prefix++;if(ev.relationship.display_exact_common_surname)stats.validated_common_plus_surname++;if(ev.relationship.surname_exactly_matches_display_suffix)stats.validated_suffix_relationship++;if(ev.cross_source_common_plus_surname_validated)stats.cross_source_common_surname_validated++;if(ev.recommended_natural_display_name)stats.retained_consensus_recommended++;if(ev.relationship.common_is_not_first_name)stats.common_differs_from_first++;if(stats.examples.length<12&&ev.confidence.includes('validated_'))stats.examples.push({person_id:ev.person_id,record_id:p.id??null,display:ev.components.display,common:ev.components.common,surname:ev.components.surname,legal:ev.components.legal||null,retained_alias:ev.retained_match_alias,confidence:ev.confidence,pools:ev.components.pools});const isTaty=ev.person_id==='24517'||low(ev.components.display)==='taty castellanos';if(isTaty)stats.taty_probe={person_id:ev.person_id,record_id:p.id??null,identity_match_source:ev.person_id==='24517'?'stable_person_id':'resolved_display_fallback',display:ev.components.display,legal:ev.components.legal||null,first:ev.components.first||null,common:ev.components.common||null,surname:ev.components.surname||null,nickname:ev.components.nickname||null,shirt_name:ev.components.shirt||null,preferred_short_name:ev.components.short||null,display_suffix_after_common:ev.relationship.display_suffix_after_common,retained_match_alias:ev.retained_match_alias,cross_source_common_plus_surname_validated:ev.cross_source_common_plus_surname_validated,recommended_natural_display_name:ev.recommended_natural_display_name,common_plus_surname_validated:ev.relationship.display_exact_common_surname&&ev.relationship.surname_exactly_matches_display_suffix,rejects_common_only:!!ev.components.common&&low(ev.components.display)!==low(ev.components.common),rejects_naive_legal_first_tokens:!!ev.components.legal&&low(ev.components.display)!==low(clean(ev.components.legal).split(' ').slice(0,2).join(' ')),legal_identity_retained_separately:!!ev.components.legal,validation_probe_only_no_display_override:true,pools:ev.components.pools};}
 try{window.FM_NAME_SCHEMA_EVIDENCE=stats;if(typeof FM_DEBUG!=='undefined'&&FM_DEBUG){FM_DEBUG.nameSchemaEvidence=stats;FM_DEBUG.nameSchemaPolicy='Resolve by stable FM person identity. Retained player-level match aliases are an independent validation source: common/known-as + football surname is cross-source validated only when a strong retained alias consensus confirms the same natural display. Legal names, nickname, shirt name and preferred short name stay separate; no evidence learner rewrites the visible display.'}}catch(_){}
 return stats}
function install(){let original;try{original=typeof applyImportedPayload==='function'?applyImportedPayload:null}catch(_){original=null}if(original&&!original.__fmNameEvidenceLearningWrapped){const wrapped=function(...args){const out=original.apply(this,args);try{if(typeof window.fmAnnotateImporterEvidence==='function')window.fmAnnotateImporterEvidence();run();if(typeof window.fmBuildImportCapabilities==='function')window.fmBuildImportCapabilities()}catch(e){console.warn('Name schema evidence learning failed',e)}return out};wrapped.__fmNameEvidenceLearningWrapped=true;try{applyImportedPayload=wrapped}catch(_){}}try{run()}catch(_){}}
window.fmStablePersonIdForNameEvidence=stablePersonId;window.fmRetainedNameAliasEvidence=retainedAliasEvidence;window.fmLearnNameSchemaEvidence=run;install();
})();
