(()=>{
'use strict';
const VERSION='new-entrant-pricing-v1-arrival-window-role';
const arr=v=>Array.isArray(v)?v:[];
const num=v=>Number(v||0)||0;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,num(v)));
const roundHalf=v=>Math.round(num(v)*2)/2;
const pid=p=>String(p?.pid??p?.player_id??p?.person_id??p?.eid??p?.id??'');
const visible=p=>!!p&&p.visible!==false&&p.competition_eligible!==false;
function quality(p){const c=p?.price_context||{};if(Number.isFinite(Number(c.quality)))return clamp(c.quality);const ca=num(p?.ca);return ca>0?clamp((ca-85)/80):0}
function roleEvidence(p){const c=p?.price_context||{},available=Math.max(0,num(c.available_matches)||num(c.observed_matches)||arr(p?.history).length),mins=Math.max(0,num(p?.minutes)),starts=Math.max(0,num(p?.starts));let share=Number(c.minutes_share),start=Number(c.start_share);if(!Number.isFinite(share))share=available?clamp(mins/(90*available)):0;if(!Number.isFinite(start))start=available?clamp(starts/available):0;share=clamp(share);start=clamp(start);const depth=clamp(c.depth_score);return {available,share,start,role:Math.max(.35*depth,.7*share+.3*start),depth}}
function project(p){const pos=String(p?.pos||''),c=p?.price_context||{},q=quality(p),team=clamp(c.team_strength),attack=clamp(c.attack_profile),r=roleEvidence(p);if(!['GK','DEF','MID','FWD'].includes(pos)||(!q&&!r.role&&!team&&!attack))return null;let raw=0,floor=4,cap=10.5;if(pos==='GK'){raw=3.9+.45*q+.9*r.role+.65*team;floor=4;cap=6}else if(pos==='DEF'){raw=4+.55*q+1*r.role+.65*attack+.8*team;floor=4;cap=8}else if(pos==='MID'){raw=4.5+.9*q+1*r.role+.75*attack+.65*team+1.7*(q**3);floor=4.5;cap=10.5}else{raw=5+.95*q+1.05*r.role+.55*attack+.75*team+1.6*(q**3);floor=4.5;cap=10.5}return {price:roundHalf(Math.max(floor,Math.min(cap,raw))),raw,q,team,attack,...r}}
function apply(payload,old){if(!payload||!old||String(payload?.meta?.import_mode||window.__FM_IMPORT_MODE_ACTIVE||'').toLowerCase()!=='update')return null;const oldMap=new Map(arr(old?.players).map(p=>[pid(p),p]).filter(([id])=>id)),examples=[];let entrants=0,repriced=0;for(const p of arr(payload?.players)){if(!visible(p))continue;const id=pid(p),prev=oldMap.get(id)||null;if(prev&&visible(prev))continue;entrants++;const pr=project(p);if(!pr)continue;const before=num(p.price);p.price=pr.price;p.model_price=pr.price;p.launch_price=pr.price;p.dynamic_price=pr.price;p.price_baseline_gw=num(payload?.meta?.latest_gameweek_with_result);p.price_change_history=[];const c=p.price_context||(p.price_context={});c.entry_pricing_v1={version:VERSION,old_price:before,new_price:pr.price,quality:Number(pr.q.toFixed(3)),team_strength:Number(pr.team.toFixed(3)),attack_profile:Number(pr.attack.toFixed(3)),available_matches:pr.available,arrival_minute_share:Number(pr.share.toFixed(3)),arrival_start_share:Number(pr.start.toFixed(3)),role_confidence:Number(pr.role.toFixed(3)),policy:'initial Fantasy entry price only; ability, club strength and role since arrival; no goals, assists, points, ratings or injury effect'};if(pr.share>=.7||pr.start>=.6){c.usage_role='new_arrival_starter';c.usage_role_floor=String(p.pos)==='MID'?5.5:String(p.pos)==='FWD'?6:String(p.pos)==='DEF'?5:4.5;c.usage_role_cap=String(p.pos)==='MID'?10.5:String(p.pos)==='FWD'?10.5:String(p.pos)==='DEF'?8:6}c.distribution_cap=pr.price;c.price=pr.price;if(before!==pr.price)repriced++;if(examples.length<20)examples.push({id,name:p.name||p.display_name,club:p.club,pos:p.pos,old_price:before,new_price:pr.price,available_matches:pr.available,minute_share:Number(pr.share.toFixed(3)),start_share:Number(pr.start.toFixed(3)),quality:Number(pr.q.toFixed(3))})}
payload.meta=payload.meta||{};payload.meta.new_entrant_pricing_v1={version:VERSION,entrants_seen:entrants,priced:examples.length,repriced,examples,policy:'newly eligible weekly arrivals receive a fair initial entry price from current ability, club strength and role in their own arrival window; this is not a weekly price movement'};return payload.meta.new_entrant_pricing_v1}
function install(){const c=window.FMCloud;if(!c||c.__newEntrantPricingV1||typeof c.publishWorld!=='function')return false;c.__newEntrantPricingV1=true;const original=c.publishWorld.bind(c);c.publishWorld=async(payload,...args)=>{if(payload!=null){let old=null;try{old=JSON.parse(JSON.stringify(c.getWorld?.()?.payload||null))}catch(_){}if(old)apply(payload,old)}return original(payload,...args)};return true}
window.FMNewEntrantPricing={version:VERSION,project,apply,install};window.addEventListener('fmcloudready',()=>setTimeout(install,0));let tries=0;const timer=setInterval(()=>{tries++;if(install()||tries>120)clearInterval(timer)},100);
})();