'use strict';
const assert=require('assert');
const fs=require('fs');
const source=fs.readFileSync('newspersistencev5.js','utf8');
assert(source.includes("news-persistence-v8-canonical-transfer-dom-authority"));
assert(source.includes("CANONICAL_DOM_IDS=new Set(['newsTransfers','newsRegistrations'])"));
assert(source.includes('if(CANONICAL_DOM_IDS.has(id))continue'));
assert(source.includes('active_statuses:active'));
assert(source.includes('applyActiveStatuses(snap.active_statuses)'));
assert(source.includes('return recoverFromPayload(reason)'));
assert(source.includes('deriveActiveStatuses'));
assert(source.includes("localStorage.removeItem(CLEAR_KEY)"));
assert(source.includes('FMNewsTransferStabilityV40?.stabilise?.()'));
assert(!source.includes('importMode()||armed()'));
assert(!source.includes('payload_version'));
const view=fs.readFileSync('newsview.js','utf8');
assert(view.includes("news-view-v6-payload-aware-clear-state"));
assert(view.includes('if(hasPayload()){markActive();return false}'));
const world=fs.readFileSync('newsworldrecovery.js','utf8');
assert(world.includes("news-world-recovery-v1-canonical-payload-authority"));
assert(world.includes('const payload=await window.FMCloud.loadWorld(true)'));
assert(world.includes('if(world)world.payload=payload'));
const cloud=fs.readFileSync('cloudapply.js','utf8');
assert(cloud.includes("cloud-apply-v2-canonical-world-beats-stale-clear-flag"));
assert(!cloud.includes('if(done||wasCleared()||'));
assert(cloud.includes('const payload=await window.FMCloud.loadWorld()'));
console.log('news lifecycle V41 persistence regression passed');
